from strategies.base import COMMON_ACTIONS, CategoryPack

PACK = CategoryPack(
    slug="dentists",
    customer_noun="patients", customer_noun_one="patient",
    visit_noun="appointment", business_noun="clinic",
    merchant_tone="peer-clinical, collegial, evidence-cited",
    customer_tone="warm-clinical, no medical claims",
    doctor_title=True,
    deliverables={
        "share_knowledge": "pull the abstract and draft a short patient-education WhatsApp you can share",
        "compliance_alert": "put together a one-page audit checklist for your team",
        "fix_dip": "draft a recall message for lapsed patients plus a fresh Google post",
        "benchmark_gap": "refresh your Google listing with a treatment post and updated photos",
        "ride_spike": "turn this into a Google post while search interest is high",
        "milestone_push": "draft a polite review request for recent patients",
        "review_response": "draft a calm public reply plus a front-desk fix",
        "competitor_response": "draft a Google post on what patients get at your clinic",
        "seasonal_play": "draft a seasonal Google post and patient WhatsApp",
        "event_play": "draft a patient WhatsApp for it",
        "renewal": "renew it on the same plan",
        "winback_merchant": "restart your profile maintenance",
        "reengage": "send over a short summary of this month's numbers",
        "verify_profile": "walk your team through verification step by step",
        "deliver_plan": "turn this into a Google post and patient WhatsApp",
        "customer_outreach_approval": "send the reminder from your clinic's number",
        "event_register": "share the registration details and set a reminder for you",
        "default": "draft it for you",
    },
    ctas={"default": "Reply YES and I'll {deliverable}.",
          "curious_ask": "Just reply with the treatment name — I'll do the rest.",
          "renewal": "Reply YES to renew — takes a minute."},
    customer_due_line="your {service} is due",
    customer_winback_line="we'd love to see you back for a check-up",
    customer_cta_confirm="Reply YES to confirm, or tell us a time that suits you",
    customer_winback_cta="Reply YES and we'll book a check-up slot for you — no commitment.",
    default_service="check-up",
    customer_emoji="🦷",
    extra_taboos=("cure", "painless guaranteed", "100% success"),
    default_growth_move="a recall push to lapsed patients",
    allowed_actions=COMMON_ACTIONS,
)
