from strategies.base import COMMON_ACTIONS, CategoryPack

PACK = CategoryPack(
    slug="gyms",
    customer_noun="members", customer_noun_one="member",
    visit_noun="session", business_noun="gym",
    merchant_tone="coach-to-operator, disciplined, motivating",
    customer_tone="motivating, no shame, no guilt",
    deliverables={
        "share_knowledge": "draft a member WhatsApp and a Google post on it",
        "compliance_alert": "put together a short checklist for your coaches",
        "fix_dip": "draft a retention challenge for current members plus a Google post",
        "benchmark_gap": "add a class-schedule post with photos to your listing",
        "ride_spike": "push a trial-class post while interest is up",
        "milestone_push": "draft a review request for your regulars",
        "review_response": "draft a public reply plus a quick fix for the floor team",
        "competitor_response": "draft a post on your coaches and community",
        "seasonal_play": "draft a member challenge and a Google post",
        "event_play": "draft a member WhatsApp for it",
        "renewal": "renew it on the same plan",
        "winback_merchant": "restart your listing and trial-class push",
        "reengage": "send a quick summary of this month's numbers",
        "verify_profile": "walk you through verification step by step",
        "deliver_plan": "turn this into a Google post and Insta carousel",
        "customer_outreach_approval": "send the note from your gym's number",
        "event_register": "share the registration details and set a reminder for you",
        "default": "draft it for you",
    },
    ctas={"default": "Reply YES and I'll {deliverable}.",
          "curious_ask": "Just reply with the class name — I'll build the post.",
          "renewal": "Reply YES to renew — takes a minute."},
    customer_due_line="it's a good time to book your next {service}",
    customer_winback_line="no pressure, and no judgment — breaks happen",
    customer_cta_confirm="Reply YES and we'll save your spot",
    customer_winback_cta="Reply YES and we'll hold a spot for you — no commitment.",
    default_service="session",
    customer_emoji="💪",
    extra_taboos=("lose weight fast", "burn fat fast"),
    default_growth_move="a retention challenge for current members",
    allowed_actions=COMMON_ACTIONS,
)
