from strategies.base import COMMON_ACTIONS, CategoryPack

PACK = CategoryPack(
    slug="pharmacies",
    customer_noun="customers", customer_noun_one="customer",
    visit_noun="order", business_noun="pharmacy",
    merchant_tone="trustworthy, precise, compliance-first",
    customer_tone="respectful, precise, no medical advice",
    deliverables={
        "share_knowledge": "draft a short customer WhatsApp on it",
        "compliance_alert": "filter your repeat-Rx list and draft the customer notice",
        "fix_dip": "draft a refill-reminder WhatsApp for repeat customers plus a Google post",
        "benchmark_gap": "add your delivery and store hours to your Google listing",
        "ride_spike": "post your delivery details on Google while search is up",
        "milestone_push": "draft a review request for regular customers",
        "review_response": "draft a courteous public reply",
        "competitor_response": "draft a post on your delivery and pharmacist support",
        "seasonal_play": "draft a counter-display list and a Google post",
        "event_play": "draft a customer WhatsApp for it",
        "renewal": "renew it on the same plan",
        "winback_merchant": "restart your listing and delivery push",
        "reengage": "send a quick summary of this month's numbers",
        "verify_profile": "walk you through verification step by step",
        "deliver_plan": "turn this into a customer WhatsApp",
        "customer_outreach_approval": "send the reminder from your pharmacy's number",
        "event_register": "share the registration details and set a reminder for you",
        "default": "draft it for you",
    },
    ctas={"default": "Reply YES and I'll {deliverable}.",
          "curious_ask": "Just reply with the product name — I'll draft the post.",
          "renewal": "Reply YES to renew — takes a minute.",
          "compliance_alert": "Reply YES and I'll {deliverable}."},
    customer_due_line="your regular medicines are due for a refill",
    customer_winback_line="we're here whenever you need your regular medicines",
    customer_cta_confirm="Reply CONFIRM and we'll keep it ready",
    customer_winback_cta="Reply YES and we'll keep your usual order ready.",
    default_service="refill",
    customer_emoji="",
    # No diagnosis, dosage or cure language (brief §5.8, pharmacies taboo list).
    extra_taboos=("cure", "diagnose", "diagnosis", "dosage", "prescribe", "side-effect free"),
    default_growth_move="a refill-reminder set-up for repeat customers",
    allowed_actions=COMMON_ACTIONS,
)
