from strategies.base import COMMON_ACTIONS, CategoryPack

PACK = CategoryPack(
    slug="restaurants",
    customer_noun="guests", customer_noun_one="guest",
    visit_noun="table", business_noun="restaurant",
    merchant_tone="busy, practical, operator-to-operator",
    customer_tone="upbeat, appetite appeal",
    deliverables={
        "share_knowledge": "draft the menu/GBP update for it",
        "compliance_alert": "put together a quick checklist for your kitchen team",
        "fix_dip": "draft a slow-day promo using your current offer plus a Google post",
        "benchmark_gap": "add a dish-and-price post with photos to your listing",
        "ride_spike": "push your best-seller as a Google post while traffic is up",
        "milestone_push": "draft a review request for this week's regulars",
        "review_response": "draft a public reply plus a fix for the delivery/kitchen team",
        "competitor_response": "draft a post on your signature dishes",
        "seasonal_play": "draft the promo banner and a Google post",
        "event_play": "draft the banner and an Insta story",
        "renewal": "renew it on the same plan",
        "winback_merchant": "restart your listing and offers push",
        "reengage": "send a quick summary of this month's covers and calls",
        "verify_profile": "walk you through verification step by step",
        "deliver_plan": "turn this into a WhatsApp you can send to offices nearby",
        "customer_outreach_approval": "send the note from your restaurant's number",
        "event_register": "share the details and set a reminder for you",
        "event_play_weekend": "draft tonight's delivery story and a banner for the next weeknight match",
        "default": "draft it for you",
    },
    ctas={"default": "Reply YES and I'll {deliverable}.",
          "curious_ask": "Just reply with the dish — I'll turn it into a post.",
          "renewal": "Reply YES to renew — takes a minute."},
    customer_due_line="your favourites are waiting",
    customer_winback_line="it's been a while — your table's waiting",
    customer_cta_confirm="Reply YES and we'll keep it ready",
    customer_winback_cta="Reply YES and we'll reserve a table for you.",
    default_service="visit",
    customer_emoji="🍽️",
    extra_taboos=("best food in town",),
    default_growth_move="a slow-day promo built on your own offer",
    allowed_actions=COMMON_ACTIONS,
)
