from strategies.base import COMMON_ACTIONS, CategoryPack

PACK = CategoryPack(
    slug="salons",
    customer_noun="clients", customer_noun_one="client",
    visit_noun="booking", business_noun="salon",
    merchant_tone="warm, practical, fellow-operator",
    customer_tone="warm, pampering, never pushy",
    deliverables={
        "share_knowledge": "draft a Google post and a client WhatsApp on it",
        "compliance_alert": "put together a short checklist for your team",
        "fix_dip": "draft a win-back WhatsApp for lapsed clients plus a fresh Google post",
        "benchmark_gap": "add a service-and-price post to your Google listing",
        "ride_spike": "push your top service as a Google post while demand is up",
        "milestone_push": "draft a review request for this week's happy clients",
        "review_response": "draft a warm public reply plus a quick fix for the team",
        "competitor_response": "draft a post showing your stylists' work",
        "seasonal_play": "draft the booking post and a client WhatsApp",
        "event_play": "draft a booking post for it",
        "renewal": "renew it on the same plan",
        "winback_merchant": "restart your profile and bookings push",
        "reengage": "send a quick summary of this month's numbers",
        "verify_profile": "walk you through verification step by step",
        "deliver_plan": "turn this into a Google post and client WhatsApp",
        "customer_outreach_approval": "send the note from your salon's number",
        "event_register": "share the registration details and block the date for your stylist",
        "default": "draft it for you",
    },
    ctas={"default": "Reply YES and I'll {deliverable}.",
          "curious_ask": "Just reply with the service name — I'll handle the post.",
          "renewal": "Reply YES to renew — takes a minute."},
    customer_due_line="your next {service} is due",
    customer_winback_line="we've missed you at the salon",
    customer_cta_confirm="Reply YES and we'll hold a slot for you",
    customer_winback_cta="Reply YES and we'll hold a slot for you — no commitment.",
    default_service="appointment",
    customer_emoji="✨",
    extra_taboos=("flawless skin guaranteed",),
    default_growth_move="a service-and-price post on Google",
    allowed_actions=COMMON_ACTIONS,
)
